<?php require 'templates/layout/header.phtml' ?>

<div class="container mt-5 d-flex justify-content-center"> 
    <form method='post' action='login' class="w-50"> 
        <?php if ($error): ?>
            <div class='alert alert-danger' role='alert'>
                <?= htmlspecialchars($error) ?> 
            </div>
        <?php endif ?>

        <div class='form-group'>
            <label for='email'>Usuario</label>
            <input type='text' class='form-control' id='email' name='email' required>
        </div>
        <div class='form-group'>
            <label for='password'>Password</label>
            <input type='password' class='form-control' id='password' name='password' required>
        </div>
        
        <button type='submit' class='btn btn-primary mt-4 btn btn-pink btn-lg ml-auto '>Login</button> 
</div>

<?php require 'templates/layout/footer.phtml' ?>
