<form action="nueva" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Deudor:</label>
                <input required name="deudor" type="text" class="form-control">
                <label>Cuota:</label>
                <input required name="cuota" type="number" class="form-control">
                <label>Cuota capital:</label>
                <input required name="cuota_capital" type="number" class="form-control">
                <label>Fecha pago:</label>
                <input required name="fecha_pago" type="date" class="form-control">

                
                <button type="submit" class="btn btn-primary mt-2">Guardar</button>
            </div>
        </div>

    </div>

</form>